INSERT INTO `categories` (`id`, `parent_id`, `name`, `slug`, `created_at`, `updated_at`)
VALUES
(13, NULL, 'Tool Storage and Organization', 'tool-storage-and-organization', NULL, NULL),
(14, NULL, 'Safety Equipment', 'safety-equipment', NULL, NULL),
(15, NULL, 'Workwear and Apparel', 'workwear-and-apparel', NULL, NULL),
(16, NULL, 'Paint and Painting Tools', 'paint-and-painting-tools', NULL, NULL),
(17, NULL, 'Measuring Tools', 'measuring-tools', NULL, NULL),
(18, NULL, 'Automotive Tools', 'automotive-tools', NULL, NULL),
(19, NULL, 'Plumbing Tools', 'plumbing-tools', NULL, NULL),
(20, NULL, 'HVAC Tools', 'hvac-tools', NULL, NULL),
(21, NULL, 'Woodworking Tools', 'woodworking-tools', NULL, NULL),
(22, NULL, 'Metalworking Tools', 'metalworking-tools', NULL, NULL),
(23, NULL, 'Masonry Tools', 'masonry-tools', NULL, NULL),
(24, 13, 'Tool Boxes', 'tool-boxes', NULL, NULL),
(25, 13, 'Tool Cabinets', 'tool-cabinets', NULL, NULL),
(26, 14, 'Work Gloves', 'work-gloves', NULL, NULL),
(27, 14, 'Knee Pads', 'knee-pads', NULL, NULL),
(28, 15, 'Protective Clothing', 'protective-clothing', NULL, NULL),
(29, 15, 'Safety Boots', 'safety-boots', NULL, NULL),
(30, 16, 'Paint Brushes', 'paint-brushes', NULL, NULL),
(31, 16, 'Paint Sprayers', 'paint-sprayers', NULL, NULL),
(32, 17, 'Laser Distance Measurers', 'laser-distance-measurers', NULL, NULL),
(33, 17, 'Measuring Tapes', 'measuring-tapes', NULL, NULL),
(34, 18, 'Automotive Diagnostic Tools', 'automotive-diagnostic-tools', NULL, NULL),
(35, 18, 'Car Jack and Lifting Equipment', 'car-jack-and-lifting-equipment', NULL, NULL),
(36, 19, 'Pipe Wrenches', 'pipe-wrenches', NULL, NULL),
(37, 19, 'Drain Cleaning Tools', 'drain-cleaning-tools', NULL, NULL),
(38, 20, 'Air Compressors', 'air-compressors', NULL, NULL),
(39, 20, 'HVAC Gauges', 'hvac-gauges', NULL, NULL),
(40, 21, 'Circular Saws', 'circular-saws', NULL, NULL),
(41, 21, 'Jigsaws', 'jigsaws', NULL, NULL),
(42, 22, 'Grinders', 'grinders', NULL, NULL),
(43, 22, 'Bench Grinders', 'bench-grinders', NULL, NULL),
(44, 23, 'Masonry Drills', 'masonry-drills', NULL, NULL),
(45, 23, 'Trowels', 'trowels', NULL, NULL),
(46, 24, 'Cordless Drills', 'cordless-drills', NULL, NULL),
(47, 24, 'Corded Drills', 'corded-drills', NULL, NULL),
(48, 25, 'Impact Drivers', 'impact-drivers', NULL, NULL),
(49, 25, 'Impact Wrenches', 'impact-wrenches', NULL, NULL),
(50, 26, 'Rotary Hammers', 'rotary-hammers', NULL, NULL),
(51, 26, 'Hammer Drills', 'hammer-drills', NULL, NULL),
(52, 27, 'Pneumatic Tools', 'pneumatic-tools', NULL, NULL),
(53, 27, 'Air Tools', 'air-tools', NULL, NULL),
(54, 28, 'Jacks and Lifting Equipment', 'jacks-and-lifting-equipment', NULL, NULL),
(55, 28, 'Car Battery Chargers', 'car-battery-chargers', NULL, NULL),
(56, 29, 'Plumbing Drain Tools', 'plumbing-drain-tools', NULL, NULL),
(57, 29, 'Pipe Benders', 'pipe-benders', NULL, NULL),
(58, 30, 'Woodworking Clamps', 'woodworking-clamps', NULL, NULL),
(59, 30, 'Router Tools', 'router-tools', NULL, NULL),
(60, 31, 'Welding Machines', 'welding-machines', NULL, NULL),
(61, 31, 'Welding Helmets', 'welding-helmets', NULL, NULL),
(62, 32, 'Measuring Wheels', 'measuring-wheels', NULL, NULL),
(63, 32, 'Digital Levels', 'digital-levels', NULL, NULL);
